name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:

env:
  CHERE_INVOKING: 1

jobs:
  test:
    name: ${{ matrix.no-coverage }} ${{ matrix.testfile }} flags=${{ matrix.gap-flags }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        no-coverage: ['']
        testfile: ['']
        gap-flags: ['']
        include:
          - no-coverage: 'no-coverage'
            testfile: ''
            gap-flags: ''
          - no-coverage: ''
            testfile: 'tst/testall.g'
            gap-flags: ''
          - no-coverage: 'no-coverage'
            testfile: ''
            gap-flags: '-A'

    steps:
      # the order of the checkout actions is important because all contents of
      # the target folder of the checkout action is removed
      - name: "Clone the Example package"
        uses: actions/checkout@v2
        with:
          repository: gap-packages/example
      - name: "Check out this repository"
        uses: actions/checkout@v2
        with:
          path: this-action/
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: ''
      - uses: gap-actions/build-pkg@v1
      - uses: ./this-action/
        with:
          NO_COVERAGE: ${{ matrix.no-coverage }}
          GAP_TESTFILE: ${{ matrix.testfile }}
          GAP_FLAGS: ${{ matrix.gap-flags }}
